@extends('front.front-layout')
@section('main-section')

   <!--============= Header Section Ends Here =============-->
   <section class="page-header bg_img oh" data-background="{{ asset('front-theme') }}/assets/images/page-header.png">
    <div class="bottom-shape d-none d-md-block">
        <img src="{{ asset('front-theme') }}/assets/css/img/page-header.png" alt="css">
    </div>
    <div class="page-left-thumb">
        <img src="{{ asset('front-theme') }}/assets/images/bg/privacy-header.png" alt="bg">
    </div>
    <div class="container">
        <div class="page-header-content cl-white">
            <h2 class="title">Our Privacy Policy</h2>
            <ul class="breadcrumb">
                <li>
                    <a href="index.php">Home</a>
                </li>
                <li>
                    <a href="#0">Pages</a>
                </li>
                <li>
                    Privacy
                </li>
            </ul>
        </div>
    </div>
</section>
<!--============= Header Section Ends Here =============-->



<!--============= Privacy Section Starts Here =============-->
<section class="privacy-section padding-top padding-bottom">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="section-header">
                    <h2 class="title">Privacy Policy</h2>
                    <p>Please read this Privacy Policy carefully before using this website</p>
                </div>
            </div>
        </div>
        <div class="row justify-content-between">
            <div class="col-lg-4">
                <aside class="sticky-menu">
                    <div class="faq-menu bg_img" data-background="{{ asset('front-theme') }}/assets/images/faq/faq-menu.png">
                        <ul id="faq-menu">
                            <li class="nav-item">
                                <a class="nav-link" href="#terms_and_condition">Terms & Conditions</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#general">Privacy Policy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#prop">Selling</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#secu">Refund Policy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#cookies">Cookies</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#data_security">Data Security</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#data_privacy">Data Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#data_use_cases">Data Use Cases</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="#info">Trademark, Copyright and Restriction</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#cooki">Product Description</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#ipaddr">Contact Us</a>
                            </li>
                        </ul>
                    </div>
                </aside>
            </div>
            <div class="col-lg-8 col-xl-7">
                <article class="mt-70 mt-lg-0">
                    <div class="privacy-item" id="terms_and_condition">
                        <h3 class="title">Terms And Condition</h3>
                        <div>
                            <p> This document is an electronic record in terms of Information Technology Act, 2000 and generated by a computer system and does not require any physical or digital signatures.
                            </p>
                            <p>
                                This document is published in compliance of and shall be governed by Indian law, including but not limited to (i) the Indian Contract Act, 1872; (ii) the Information Technology Act, 2000, the rules, regulations, guidelines and clarifications framed thereunder; (iii) the Payment and Settlement Systems Act, 2007 and applicable rules, regulations and guidelines made thereunder; and (iv) Reserve Bank of India act, 1934 and the applicable rules, regulations and guidelines made thereunder for the bank for issuance and operation of pre-paid payment instrument and for money transfer (V) Master Direction- Know Your Customer(KYC) Direction, 2016 issued by RBI.
                            </p>
                            <p>
                                This document is disclosed in compliance with Section 21 of Payment and Settlement Systems Act, 2007 and as required to be disclosed under policy guidelines on issuance and operation of pre-paid payment instrument in India.</p>
                            <p>
                                This agreement is a legally binding document between you and the bank (both Terms defined below).
                                The Terms of this document will be effective upon your issuance of pre-paid payment instrument by
                                the bank or your usage of pre-paid payment instrument and will govern the relationship between you and the Bank
                                for the Use of DHANNIPAY DIGITAL MARKETING OPC PVT LTD (defined below). These Terms are in addition to and not
                                in derogation with Terms and Conditions of any other product or serives of the bank.
                            </p>
                        </div>
                    </div>
                    <div class="privacy-item" id="general">

                        <h3 class="title">Privacy Policy</h3>
                        <p>We understand the need for protection for Your privacy policy as a very important principle. We understand clearly that You and Your Personal Information is one of Our most important assets. We store and process Your Information including any sensitive financial information collected (as defined under the Information Technology Act, 2000), if any, on computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act 2000 and Rules thereunder.</p>
                        <p>

                            We and our affiliates will share / sell/transfer/license/covey some or all of your personal information with another business entity should we (or our assets) plan to merge with or are acquired by that business entity, or re-organization, amalgamation, restructuring of business or for any other reason whatsoever. Should such a transaction or situation occur, the other business entity or the new combined entity will be required to follow the privacy policy with respect to your personal information? Once you provide your information to us, you provide such information to us and our affiliate and we and our affiliate may use such information to provide you various services with respect to your transaction whether such transactions are conducted on www.divyaenterprises.click or with a third party merchant’s or third party merchant’s website.</p>
                    </div>

                    <div class="privacy-item" id="prop">
                        <h3 class="title">Selling</h3>
                        <p>As a registered seller, you are allowed to list item(s) for sale on the Website in accordance with the Policies which are incorporated by way of reference in this Terms of Use. You must be legally able to sell the item(s) you list for sale on our Website. You must ensure that the listed items do not infringe upon the intellectual property, trade secret or other proprietary rights or rights of publicity or privacy rights of third parties. Listings may only include text descriptions, graphics and pictures that describe your item for sale. All listed items must be listed in an appropriate category on the Website. All listed items must be kept in stock for successful fulfilment of sales. </p>
                        <p>The listing description of the item must not be misleading and must describe the actual condition of the product. If the item description does not match the actual condition of the item, you agree to refund any amounts that you may have received from the Buyer. You agree not to list a single product in multiple quantities across various categories on the Website. Divya Enterprises reserves the right to delete such multiple listings of the same product listed by you in various categories.
                            .</p>
                    </div>
                    <div class="privacy-item" id="secu">
                        <h3 class="title">Refund Policy</h3>
                        <p>Mobile/DTH/Data Card Recharge Refund Policies</p>
                        <p>All sales of Recharge are final and there will be no refund or exchange permitted. Please be advised that You are
                            responsible for the mobile number or DTH account number you purchase Recharge for and all charges that result from
                            those purchases. Divya Enterprises is not responsible for any purchase of Recharge for an incorrect mobile number or DTH
                            account number.</p>

                        <p>However, in a case where a transaction has been completed by you on the Site, and money has been charged to your card
                            or bank account but a Recharge has not delivered within 24 hours of your completion of the transaction then you may
                            inform us by sending us an email on Divya Enterprises or posting us a message on the Contac us page. In such a scenario you
                            will be entitled to a full refund. We request you to include in the email the following details - the mobile number
                            or DTH account number, operator name, Recharge value, Transaction date and Order Number. Divya Enterprises shall investigate
                            the incident and if it is found that money was indeed charged to your card or bank account without delivery of the
                            Recharge then you will be refunded the money within 7 to 10 working days from the date of the receipt of your email.
                        </p>

                        <p>For cases if you are doing recharge from your Divya Enterprises account balance and you have received a success confirmation
                            but not received a recharge or any other case you are welcome to log a complaint by opening a support ticket on our
                            contact us page and we will provide you a quick resolution.</p>

                        </p>Refund Policy for B2B Customer :</p>
                        <p>B2B customer, takes the balance. In any event, the balance will not return.</p>
                        <p>Kindly note, in all cases our liability is only restricted to providing you a valid recharge or refund to the extent
                            of payment received by us. We shall not be responsible for any other claim or consequential liability arising out of
                            a failed recharge on our system.
                            Happy Recharging….!</p>

                    </div>
                    <div class="privacy-item" id="cookies">
                        <h3 class="title">Cookies</h3>
                        <p>This site is controlled and operated by Divya Enterprises and products are sold by respective Sellers. All material on this site, including images, illustrations, audio clips, and video clips, is protected by copyrights, trademarks, and other intellectual property rights. Material on the Website is solely for Your personal, non-commercial use. You must not copy, reproduce, republish, upload, post, transmit or distribute such material in any way, including by email or other electronic means and whether directly or indirectly and You must not assist any other person to do so. Without the prior written consent of the owner, modification of the materials, use of the materials on any other website or networked computer environment or use of the materials for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks and other proprietary rights, and is prohibited. Any use for which You receive any remuneration, whether in money or otherwise, is a commercial use for the purposes of this clause.</p>

                    </div>
                    <div class="privacy-item" id="data_security">
                        <h3 class="title">Data Security</h3>
                        <p>It is important for us to secure your individual data. So, we take all suitable and legitimate measures to protect your data from all sorts of theft and misuse. We ensure that your personal data is safe and secure with us. We allow only authorized staff to get access to your information so that no data breach at all.</p>
                    </div>
                    <div class="privacy-item" id="data_privacy">
                        <h3 class="title">Data Privacy</h3>
                        <p>We collect your data only for improving your experience, not for selling or trading purpose. We don’t share your personal data with 3rd parties for commercial gains. We ensure the privacy and accuracy of your data with restricted access given only to concerned authorities.</p>
                    </div>
                    <div class="privacy-item" id="data_use_cases">
                        <h3 class="title">Data Use Cases</h3>
                        <p>Your personal data is stored and processed by us for legitimate interests and efficient service delivery following the law of the land. We may use your information for the below purposes: • To communicate with clients, • To improve our services and website experience, • To provide and maintain our services, and • To offer necessary data to the 3rd party for business service and operations.</p>
                    </div>


                    <div class="privacy-item" id="info">
                        <h3 class="title">Trademark, Copyright and Restriction

                        </h3>
                        <p>This site is controlled and operated by Divya Enterprises and products are sold by respective Sellers. All material on this site, including images, illustrations, audio clips, and video clips, is protected by copyrights, trademarks, and other intellectual property rights. Material on the Website is solely for Your personal, non-commercial use. You must not copy, reproduce, republish, upload, post, transmit or distribute such material in any way, including by email or other electronic means and whether directly or indirectly and You must not assist any other person to do so. Without the prior written consent of the owner, modification of the materials, use of the materials on any other website or networked computer environment or use of the materials for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks and other proprietary rights, and is prohibited. Any use for which You receive any remuneration, whether in money or otherwise, is a commercial use for the purposes of this clause.</p>

                    </div>
                    <div class="privacy-item" id="cooki">
                        <h3 class="title">Product Description</h3>
                        <p>Divya Enterprises we do not warrant that the Product description or other content of this Website is accurate, complete, reliable, current, or error-free and assumes no liability in this regard.</p>

                    </div>
                    <div class="privacy-item" id="ipaddr">
                        <h3 class="title">Contact Us</h3>
                        <p>Please contact us for any questions or comments (including all inquiries unrelated to copyright infringement) regarding this Website.
                            <br><br>
                            Mr.
                            <br>
                            DHANNIPAY DIGITAL MARKETING OPC PVT LTD
                            <br>
                            37/38 NIRANJAN PARK NANGLI DEYRI
                            <br>
                            NEW DELHI 110043, India
                            <br>
                            Phone: +91 755-053-5555
                            <br>
                            Email: support@divyaenterprises.click
                            <br>
                            Time: Mon – Sat (9:00 – 18:00)

                        </p>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>
<!--============= Privacy Section Ends Here =============-->


@endsection